no-greeting
no-emit-version
default-key A8AF34D58947F29794712FB0008222C3AEE7208A

# Include keys that have been revoked when searching.
keyserver-options include-revoked
#keyserver

encrypt-to 6F442D02

# List all keys (or the specified ones) along with their fingerprints
with-fingerprint

# list of personal digest preferences. When multiple ciphers are supported by
# all recipients, choose the strongest one
personal-digest-preferences SHA512 SHA384 SHA256 SHA224
